service: santa

frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  apiGateway:
    shouldStartNameWithService: true
  stage: dev
  region: us-east-2

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  hello:
    handler: bin/hello
    events:
      - http:
          path: hello
          method: post
  # world:
  #   handler: bin/world
  #   events:
  #     - http:
  #         path: world
  #         method: get
